# Generated by Django 4.0.4 on 2022-05-29 15:32

import django.core.validators
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_ano_letivo_projeto_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagem',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='pontuacao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.posts_resolution_path),
        ),
    ]
