# Generated by Django 4.0.4 on 2022-06-06 23:31

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_linguagem_nome_alter_pontuacaoquizz_pontuacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to=portfolio.models.posts_resolution_path)),
                ('relatorio', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('video', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
